"""Initial schema

Revision ID: 9ca5dd905ba6
Revises: da1fcaccc39d
Create Date: 2025-11-07 19:09:02.914114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca5dd905ba6'
down_revision = 'da1fcaccc39d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_attempts', sa.Column('exam_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_exam_attempts_exam_id'), 'exam_attempts', ['exam_id'], unique=False)
    op.create_foreign_key(None, 'exam_attempts', 'exams', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_exam_attempts_exam_id'), table_name='exam_attempts')
    op.drop_column('exam_attempts', 'exam_id')
    # ### end Alembic commands ###
